services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "4173:4173"
    environment:
      - DB_UID=${DB_UID}
      - DB_PW=${DB_PW}
      - DB=${DB}
      - DB_IP=${DB_IP}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - sqlserver
    networks:
      - marcadas-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_PW}
      ACCEPT_EULA: "Y"
    networks:
      - marcadas-net
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${DB_PW}", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  marcadas-net:

volumes:
  sqlserver-data:
    driver: local
