export {default as BtnDescargar} from "$lib/components/BtnDescargar.svelte"
export {default as DataTable} from "$lib/components/DataTable.svelte"
export {default as DatePicker} from "$lib/components/DatePicker.svelte"
export {default as LoadingIcon} from "$lib/components/LoadingIcon.svelte"
export {default as MainOptions} from "$lib/components/MainOptions.svelte"
export {default as RangeDatePicker} from "$lib/components/RangeDatePicker.svelte"
export {default as TabsDepartamento} from "$lib/components/TabsDepartamento.svelte"
